In [1]:
import numpy as np

In [5]:
np.arange(10, 49) #faz um array de 10 a 48

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [6]:
np.zeros(10) #faz um array com 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.eye(5,5) #matriz identidade 5x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.arange(0, 100, 5) #vai de 0 a 100 pulando de 5 em 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [14]:
np.ones((4,3)) #martiz so com um 4x3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.random.rand(10) #randomiza 10 numeros entr 0 e 1

array([0.26828725, 0.68242151, 0.16992785, 0.31612709, 0.07300445,
       0.41776925, 0.22196247, 0.88032814, 0.39413658, 0.95147311])

In [17]:
np.random.randn(25) #pega 25 numeros aleatorios

array([ 1.01260806,  0.29573629, -1.3538099 , -0.96416432,  0.22934577,
       -0.48378665,  0.59971808, -1.56817428, -1.18646192,  0.47679511,
        0.90777213,  0.22891669,  1.19591361,  1.7696811 , -0.69463495,
        0.82547967, -0.54606318,  0.29224449,  0.20190487, -0.44943034,
        0.61960594, -0.14830235, -0.18030282,  0.83400425, -1.09967951])

In [21]:
np.random.rand(10) * 100 #pega 10 numero aleatorios e multiplica por 100

array([45.99482547, 13.11572824, 66.83346768, 24.30784477, 14.30073367,
       37.02299397,  8.58606396, 14.31853771, 70.20915917, 45.84755373])

In [30]:
arr = np.arange(1, 21) #faz um array indo de 1 a 20

In [31]:
arr.reshape((4, 5)) #joga o array em forma de matriz 4x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [62]:
arr = np.arange(1, 26).reshape(5,5) #faz um array de 1 ate 25 e joga pra uma matriz 5x5

In [63]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
arr[2, 2] #pega o numero que ta na linha 2 e na coluna 2

np.int64(13)

In [65]:
arr[4:][:] #pega a ultima linha da matriz

array([[21, 22, 23, 24, 25]])

In [66]:
arr[1:3, 1:3] #pega a linha 1 e 2 e as coluna 1 e 2

array([[ 7,  8],
       [12, 13]])

In [67]:
arr[:,0] = 0 #define a 1 coluna como 0

In [68]:
arr

array([[ 0,  2,  3,  4,  5],
       [ 0,  7,  8,  9, 10],
       [ 0, 12, 13, 14, 15],
       [ 0, 17, 18, 19, 20],
       [ 0, 22, 23, 24, 25]])

In [69]:
arr[arr > 20] #pega so os numeros maiores q 20 da matriz

array([22, 23, 24, 25])

In [70]:
arr + 100 #soma 100 em todos os indices da matriz

array([[100, 102, 103, 104, 105],
       [100, 107, 108, 109, 110],
       [100, 112, 113, 114, 115],
       [100, 117, 118, 119, 120],
       [100, 122, 123, 124, 125]])

In [71]:
arr.mean() #pega a media da matriz

np.float64(10.8)

In [72]:
arr.std() #pega o DP dos valores da matriz

np.float64(8.37615663654877)

In [73]:
arr.sum(axis = 0) #soma as coluna da matriz

array([ 0, 60, 65, 70, 75])

In [74]:
arr.argmax() #pega o indice de onde ta o maior numero da matriz

np.int64(24)