Importe Numpy como np

In [5]:
import numpy as np

Crie uma matriz de 10 zeros

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Crie uma matriz de 10 ones

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Crie uma matriz de 10 cincos

In [9]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Crie um array de inteiros de 10 ate 50

In [10]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Crie um array dos numeros pares de 10 ate 50

In [11]:
np.arange(10,50, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

Crie uma matriz 3x3 com valores variando de 0 ate 8

In [13]:
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Crie uma matriz identidade 3x3

In [14]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use numpy para gerar numeros aleatorios entre 0 e 1

In [16]:
np.random.rand(10)

array([0.08310056, 0.88887204, 0.02373818, 0.29585741, 0.77393946,
       0.35932323, 0.90134788, 0.46321073, 0.71292421, 0.39981731])

Use numpy para gerar um array de 25 numeros aleatorios tirados de uma distribuicao normal

In [17]:
np.random.randn(25)

array([-0.08539663,  1.3859706 ,  1.11637725,  2.25835322, -0.51712544,
        0.12251454, -0.38943409, -0.66617911,  0.73291948, -2.49758155,
        1.0194581 ,  0.18897429, -1.65263544, -1.37668358, -0.59322238,
       -0.40884861,  0.05238518, -0.49368748, -1.74942517,  0.27099481,
        0.79747271, -0.53535156,  0.13903387, -2.00846903,  0.40119739])

Crie a seguinte matriz:

In [18]:
np.arange(0.01, 1.01, 0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

Crie um array de tamanho 20 igualmente espacado entre 0 e 1

In [19]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

SEGUNDO VIDEO

Agora voce recebera algumas matrizes e sera solicitado a replicar as saidas resultantes da matriz:

In [21]:
mat = np.arange(1, 26).reshape(5, 5)

In [22]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [24]:
mat[3,4]

np.int64(20)

In [28]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [29]:
mat[4, :]

array([21, 22, 23, 24, 25])

In [30]:
mat[3:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Agora faca o seguinte

Obter a soma de todos os valores no "mat"

In [32]:
mat.sum()

np.int64(325)

Obter o desvio padrao dos valores em mat

In [33]:
mat.std()

np.float64(7.211102550927978)

Obter a soma de todas as colunas em mat

In [34]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])