In [1]:
import numpy as np

In [2]:
minha_lista = [1, 2, 3] #defino uma lista

In [3]:
minha_lista

[1, 2, 3]

In [4]:
np.array(minha_lista)

array([1, 2, 3])

tranforma a lista para um array numpy

In [5]:
minha_matriz = [1,2,3], [4,5,6], [7,8,9]

In [6]:
np.array(minha_matriz) #transoformo minha matriz em um array numpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10) #cria um array com 10 indices a partir do 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2) #vai pulando de 2 em 2, para o indice total 10

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3) #cria um array de 3 zeros

array([0., 0., 0.])

In [10]:
arr = np.zeros(3) #define arr como um array de 3 zeros

In [11]:
arr

array([0., 0., 0.])

In [12]:
arr = np.zeros((5,5)) #cria uma matriz de zeros 5x5

In [13]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((3,3)) #uma matriz 3x3 com 1 em cada valor

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.eye(4) #matriz identidade 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.linspace(0, 10, 3) #de 0 a 10 pega 3 valores com espacos iguais entre eles

array([ 0.,  5., 10.])

In [20]:
np.random.rand(5) #pega 5 numeros de forma aleatoria entre 0 e 1

array([0.10624201, 0.23967658, 0.29999708, 0.06072671, 0.570102  ])

In [21]:
np.random.rand(5) * 100 #so multiplica por 100 a operacao anterior

array([36.45288459, 58.6735899 , 54.72946609,  1.4620859 , 78.59973654])

In [22]:
np.random.rand(5, 4, 3) #cria 5 matrizes, cada uma com 4 linhas e 3 colunas, isso forma um cubo

array([[[0.11539976, 0.97867191, 0.94731932],
        [0.90244024, 0.78991687, 0.0406859 ],
        [0.31864996, 0.66435128, 0.85363968],
        [0.03049864, 0.41387729, 0.12407293]],

       [[0.5609729 , 0.3328083 , 0.32797817],
        [0.53931618, 0.4201428 , 0.28296367],
        [0.98029035, 0.52480441, 0.89456096],
        [0.7441242 , 0.71508653, 0.28771663]],

       [[0.05134487, 0.9194561 , 0.74882222],
        [0.68434824, 0.69804826, 0.1646978 ],
        [0.47249551, 0.94734398, 0.76762427],
        [0.45435266, 0.84221294, 0.09365503]],

       [[0.56140059, 0.04274979, 0.98214967],
        [0.21874415, 0.27215915, 0.29931853],
        [0.03403934, 0.02793478, 0.19321963],
        [0.23753918, 0.35526399, 0.07639806]],

       [[0.57161084, 0.05560177, 0.65625531],
        [0.79861493, 0.00425671, 0.40472876],
        [0.87420814, 0.13809255, 0.84445417],
        [0.26464468, 0.45735479, 0.81348493]]])

In [23]:
np.random.randn(4) #pega numeros aleatorios sem limite

array([ 1.71471497, -0.40425978,  1.2516539 ,  0.74530161])

In [24]:
np.random.randint(0, 100, 10) #gera 10 numeros de 0 a 100 aleatoriamente

array([96, 42, 55, 62, 24, 48, 10, 34, 87, 76])

In [25]:
np.random.rand(5) * 100 #gera 5 numero aleatorios de 0 a 1 e dps mul

array([49.92804765, 74.78764867, 65.62587768, 88.88758321, 60.49972676])

In [27]:
np.round(np.random.rand(5) * 100, 0) #pega 5 numero aleatorio e multiplica por 100, e dps arredonda

array([43., 74., 26., 97., 89.])

In [28]:
arr = np.random.rand(25) #pega 25 numeros aleatorios

In [29]:
arr

array([0.77346422, 0.45904929, 0.55980734, 0.46308429, 0.19151866,
       0.25633055, 0.35010396, 0.75047369, 0.97852813, 0.96491526,
       0.7746135 , 0.78923235, 0.6329348 , 0.88483714, 0.54102091,
       0.20897442, 0.23372585, 0.81715356, 0.22899941, 0.20398888,
       0.7914885 , 0.88190604, 0.82079922, 0.7065947 , 0.07133147])

In [30]:
arr.reshape((5,5)) #joga pra uma matriz 5x5

array([[0.77346422, 0.45904929, 0.55980734, 0.46308429, 0.19151866],
       [0.25633055, 0.35010396, 0.75047369, 0.97852813, 0.96491526],
       [0.7746135 , 0.78923235, 0.6329348 , 0.88483714, 0.54102091],
       [0.20897442, 0.23372585, 0.81715356, 0.22899941, 0.20398888],
       [0.7914885 , 0.88190604, 0.82079922, 0.7065947 , 0.07133147]])

In [33]:
arr = arr.reshape((5,5)) #arr agora e uma matriz 5x5

In [34]:
arr.shape #fala a forma do array

(5, 5)

In [37]:
arr.max() #pega o maior numero do array

np.float64(0.978528133469796)

In [38]:
arr.min() #pega o menor numero do array

np.float64(0.07133147189012978)

In [39]:
arr.argmax() #pega em qual indice ta o maior numero

np.int64(8)

In [40]:
arr.argmin() #pega em qual indice ta o menor numero

np.int64(24)

SEGUNDO VIDEO:

In [41]:
arr = np.arange(0, 30, 3)

In [42]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [43]:
arr[3]

np.int64(9)

In [45]:
arr[2:5]

array([ 6,  9, 12])

In [46]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [47]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [48]:
arr[2:] = 100

In [49]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [50]:
arr = np.arange(50).reshape(5, 10)

In [51]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [53]:
arr2 = arr[:3]

In [54]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [55]:
arr2[:] = 100

In [56]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [57]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [58]:
arr2 = arr[:3].copy()

In [59]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [60]:
arr[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [62]:
bool = arr > 50

In [63]:
arr[bool]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [64]:
array = np.linspace(0, 100, 30)

In [65]:
array

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [66]:
array.shape

(30,)

In [67]:
array = array.reshape(3, 10)

In [68]:
array.shape

(3, 10)

In [69]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [70]:
array[0:2, 2]

array([ 6.89655172, 41.37931034])

3 VIDEO

In [2]:
arr = np.arange(0, 16)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [7]:
arr / arr

/tmp/ipykernel_24816/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [8]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [9]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115])

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [12]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [13]:
np.mean(arr)

np.float64(7.5)

In [14]:
np.std(arr)

np.float64(4.6097722286464435)

In [15]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [16]:
np.max(arr)

np.int64(15)

In [17]:
np.min(arr)

np.int64(0)

In [19]:
arr.max()

np.int64(15)

In [20]:
arr.min()

np.int64(0)