In [1]:
import pandas as pd #import

In [2]:
x = pd.read_csv('entradas_breast.csv') #le o csv

In [3]:
x #print do csv

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.12380,0.18660,0.2416,186.0000,275.0000,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.14440,0.42450,0.4504,243.0000,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,173.00000
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,198.00000,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.13740,205.00000,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,111.00000,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.45,26.40,166.10,2027.0,141.00000,0.21130,0.4107,0.2216,206.0000,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,144.00000,0.09791,0.1752,0.05533,...,23.69,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,159.0000,0.05648,...,18.98,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,277.00000,0.35140,152.00000,0.2397,0.07016,...,25.74,39.42,184.60,1821.0,165.00000,0.86810,0.9387,265.0000,0.4087,124.00000


In [4]:
y = pd.read_csv('saidas_breast.csv')
y #le e printa

,0
0,0
1,0
2,0
3,0
4,0
...,...
564,0
565,0
566,0
567,0


In [5]:
import sklearn
from sklearn.model_selection import train_test_split #imports

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.25) #divide os dados em treino e teste

In [7]:
X_train.shape #o tamanho do X de treino

(426, 30)

In [8]:
X_test.shape #tamanho do X de teste

(143, 30)

In [10]:
import tensorflow as tf
from tensorflow.keras.models import Sequential #imports

In [11]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')
]) #criando a rede neural em si com os algoritimos e a camada oculta

I0000 00:00:1779547989.101266   28345 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 4118 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 6GB Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6


In [12]:
rede_neural.summary() #ver como a rede neural esta criada

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 513 (2.00 KB)

 Trainable params: 513 (2.00 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
rede_neural.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['binary_accuracy']) #compilando a rede

In [16]:
rede_neural.fit(X_train, Y_train, batch_size = 10, epochs = 100) #treinando ela

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.6901 - loss: 1.7162 
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7700 - loss: 1.0201 
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7887 - loss: 0.9758 
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8545 - loss: 0.5903 
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7864 - loss: 0.8169 
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8568 - loss: 0.5780 
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8944 - loss: 0.4337 
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8169 - loss: 0.9320 
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8732 - loss: 0.4431 
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9014 - loss: 0.3152 
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy

In [17]:
previsoes = rede_neural.predict(X_test) #fazendo as previsoes

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


In [19]:
previsoes = previsoes > 0.5 #pegando so as acima de 0.5

In [20]:
previsoes #a linha anterior jogou os valores pra true ou false pra comparar com o valor real do Y q esta embaixo

array([[ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [

In [21]:
Y_test #Y real pra comparar com o X

,0
268,1
352,0
237,0
515,1
306,1
...,...
188,1
259,0
366,0
302,0


In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix #imports

In [25]:
accuracy_score(Y_test, previsoes) #vendo a acuracia

0.9090909090909091

In [26]:
confusion_matrix(Y_test, previsoes) #jogando pra matriz de confusao

array([[49, 10],
       [ 3, 81]])

In [27]:
49 + 81, 3 + 10

(130, 13)

In [28]:
130 / 143, 13 / 143 #somas e divisoes pra mostrar como foi calculado os valores anteriores

(0.9090909090909091, 0.09090909090909091)

In [29]:
rede_neural.evaluate(X_test, Y_test) #vendo quanto ela pontuou comparando os valores

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - binary_accuracy: 0.9091 - loss: 0.4055


[0.4054584503173828, 0.9090909361839294]

# Adicionando mais camadas

In [30]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')
]) #criando mais uma camada oculta

In [31]:
rede_neural.summary() #msm coisa denovo, vendo como ela foi criada

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue = 0.5) #defiinindo um otimizador

In [33]:
rede_neural.compile(optimizer = otimizador, loss = 'binary_crossentropy', metrics = ['binary_accuracy']) #compilando ela usando o otimizador anterior

In [35]:
rede_neural.fit(X_train, Y_train, batch_size = 10, epochs = 100) #treinando 

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8545 - loss: 0.5213 
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8404 - loss: 0.6184 
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8638 - loss: 0.5562 
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8216 - loss: 0.6557 
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8474 - loss: 0.5481 
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8357 - loss: 0.5561 
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8239 - loss: 0.5980 
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8380 - loss: 0.5061 
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8756 - loss: 0.5151 
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8380 - loss: 0.5735 
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy

In [36]:
rede_neural.evaluate(X_test, Y_test) #pontuacao

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - binary_accuracy: 0.7273 - loss: 2.8889


[2.888857364654541, 0.7272727489471436]

In [39]:
pesos0 = rede_neural.layers[0].get_weights() #vendo os pesos
pesos0

[array([[ 2.65183300e-01,  4.34310548e-02, -6.68541074e-01,
         -1.79246306e-01,  3.80128682e-01,  1.00262478e-01,
         -3.78358662e-02, -5.52572720e-02,  2.84750640e-01,
         -1.69818878e-01,  4.31555927e-01, -1.46236448e-02,
         -5.72967529e-01,  1.18278220e-01,  4.34828550e-01,
         -5.14235020e-01],
        [ 3.06860656e-01,  1.67038828e-01, -3.82459551e-01,
         -2.53416508e-01,  2.20276311e-01, -7.54185161e-03,
         -8.47308934e-02,  3.79734254e-03,  3.37823004e-01,
          9.88873243e-02,  1.23829320e-01, -8.15397501e-02,
         -3.28272372e-01,  1.88101292e-01,  3.81596208e-01,
         -3.86350244e-01],
        [ 1.25536323e-01,  9.85483527e-02, -1.42386973e-01,
         -4.27784435e-02,  2.82607879e-02, -1.17663490e-02,
         -3.03927101e-02,  3.11048143e-02,  7.58134127e-02,
         -1.10116433e-02,  2.66725063e-01, -4.73685935e-02,
         -2.13929281e-01, -2.41854740e-03,  9.97563750e-02,
          9.61201414e-02],
        [-5.1880750

In [40]:
len(pesos0) #tamanho dos pesos

2

In [41]:
len(pesos0[1]) #tamanhio dos pesos0 na posicao 1

16

In [42]:
pesos0[0] #pesos 0 posicao 0 

array([[ 2.65183300e-01,  4.34310548e-02, -6.68541074e-01,
        -1.79246306e-01,  3.80128682e-01,  1.00262478e-01,
        -3.78358662e-02, -5.52572720e-02,  2.84750640e-01,
        -1.69818878e-01,  4.31555927e-01, -1.46236448e-02,
        -5.72967529e-01,  1.18278220e-01,  4.34828550e-01,
        -5.14235020e-01],
       [ 3.06860656e-01,  1.67038828e-01, -3.82459551e-01,
        -2.53416508e-01,  2.20276311e-01, -7.54185161e-03,
        -8.47308934e-02,  3.79734254e-03,  3.37823004e-01,
         9.88873243e-02,  1.23829320e-01, -8.15397501e-02,
        -3.28272372e-01,  1.88101292e-01,  3.81596208e-01,
        -3.86350244e-01],
       [ 1.25536323e-01,  9.85483527e-02, -1.42386973e-01,
        -4.27784435e-02,  2.82607879e-02, -1.17663490e-02,
        -3.03927101e-02,  3.11048143e-02,  7.58134127e-02,
        -1.10116433e-02,  2.66725063e-01, -4.73685935e-02,
        -2.13929281e-01, -2.41854740e-03,  9.97563750e-02,
         9.61201414e-02],
       [-5.18807508e-02, -1.13661690e

In [43]:
len(pesos0[0]) #tamanho

30

In [45]:
pesos1 = rede_neural.layers[1].get_weights()
pesos1 #pegando os pesos na posicao 1

[array([[ 5.31063735e-01,  3.38728651e-02, -1.31294593e-01,
         -1.44690387e-02, -6.48299512e-03, -8.77666697e-02,
          5.48651338e-01,  8.44712630e-02, -6.59096017e-02,
          6.08044714e-02, -1.22114882e-01, -2.66019642e-01,
         -1.34744480e-01, -5.28127477e-02,  1.15222991e-01,
         -4.13084105e-02],
        [ 2.23467290e-01, -1.59807187e-02,  7.62550160e-02,
          3.48081104e-02, -1.15255728e-01,  1.07980043e-01,
          1.50675386e-01, -2.72850841e-02,  6.83971448e-03,
         -1.31550580e-01, -6.24094717e-02, -1.58054277e-01,
          1.59389123e-01, -5.64666763e-02,  2.43753940e-02,
          1.06180646e-01],
        [ 3.52217667e-02, -4.31690998e-02, -8.81058350e-02,
         -3.63677666e-02, -1.04400374e-01, -1.57532934e-03,
          1.84349008e-02, -1.08702652e-01, -8.92238468e-02,
         -6.97676539e-02,  2.09435672e-02,  6.53701350e-02,
          1.29115298e-01,  1.75692737e-01,  4.55517359e-02,
          2.84958243e-01],
        [-2.8964728

In [47]:
pesos2 = rede_neural.layers[2].get_weights() #pesos na posicao 2
pesos2

[array([[ 0.17057687],
        [-0.57522064],
        [-0.30967948],
        [-0.3791007 ],
        [-0.44659317],
        [-0.51992667],
        [ 0.23948976],
        [-0.5482887 ],
        [-0.2924064 ],
        [-0.4245076 ],
        [ 0.21390937],
        [ 0.20588812],
        [-0.15368968],
        [-0.04636224],
        [-0.68295014],
        [ 0.27224606]], dtype=float32),
 array([0.46337187], dtype=float32)]