In [17]:
import torch 
import plotly.graph_objs as go
import plotly.offline as pyo
#imports

In [14]:
sample = torch.tensor([10, 11]) #faz um vetor
sample.shape #pega o formato do vetor q e 2, pq so tem 2 numeros no vetor

torch.Size([2])

In [15]:
sample #printa

tensor([10, 11])

In [11]:
x = torch.tensor([[10,11], [1,2]]) #faz uma matriz 2x2
x.shape #ve o fomrato

torch.Size([2, 2])

In [12]:
x #printa

tensor([[10, 11],
        [ 1,  2]])

In [9]:
y = torch.tensor([[10],[11]]) #matriz de uma coluna so
y.shape #ve o formato

torch.Size([2, 1])

In [13]:
y #printa

tensor([[10],
        [11]])

In [22]:
a = torch.tensor([[[1,2], [3,4], [5,6], [7,8]]]) #matriz 3D

x_vals = []
y_vals = []
z_vals = [] #listas pra cada valor
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        for k in range(a.shape[2]): #vai nas dimensoes salvando nas listas
            x_vals.append(i)
            y_vals.append(j)
            z_vals.append(k)

trace = go.Scatter3d( 
    x = x_vals,
    y = y_vals,
    z = z_vals, #pega as listas preenchidas
    mode = 'markers', #so os pontos
    marker = dict(
        size = 5, #tamanho dos pontos
        color = a.flatten(), 
        colorscale = 'Viridis', #cor de cada ponto
        opacity = 0.8 #opacidade
    )
)
    
layout = go.Layout( #define o layout da figura
    margin = dict(l = 0, r = 0, b = 0, t = 0), #margem
    scene = dict( #titulos
        xaxis = dict(title = 'Dimension 1'),
        yaxis = dict(title = 'Dimension 2'),
        zaxis = dict(title = 'Dimension 3')
    )
)

fig = go.Figure(data = [trace], layout = layout) #cria a figura
pyo.plot(fig, filename = 'tensor.html') #e coloca num html

'tensor.html'

Abrindo em uma sessão de navegador existente.
