In [1]:
import torch

In [2]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]]) #matriz

In [3]:
x #print

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [4]:
x.shape #formato de x

torch.Size([2, 4])

In [5]:
x*10 #multiplica todos os numeros por 10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [6]:
x.add(10) #soma 10 pra todos os numeros

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [7]:
x #print

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [8]:
x.shape #formato

torch.Size([2, 4])

In [10]:
x.view(4,2) #reshape pra uma matriz de duas colunas e 4 linhas

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [11]:
a = torch.ones(2,1,10) #2 pilhas com cada tendo uma linha e 10 colunas

In [12]:
a #pega o formato

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [14]:
print(f"This is the shape before squeezing: {a.shape}")
squeezed = a.squeeze(1)
print(f"This is the shape after squeezing: {squeezed.shape}") #remove a dimensao de indice 1 se ela tiver tamanho 1

This is the shape before squeezing: torch.Size([2, 1, 10])
This is the shape after squeezing: torch.Size([2, 10])


In [15]:
a = torch.ones(2,2,10)
print(f"This is the shape before squeezing: {a.shape}")
squeezed = a.squeeze(1)
print(f"This is the shape after squeezing: {squeezed.shape}") #nao consegue remover poois nao tem tamanho 1

This is the shape before squeezing: torch.Size([2, 2, 10])
This is the shape after squeezing: torch.Size([2, 2, 10])


In [16]:
a = torch.ones(2,3,1)
print(f"This is the shape before squeezing: {a.shape}")
squeezed = a.squeeze(2)
print(f"This is the shape after squeezing: {squeezed.shape}")  #remove pq o 2 indice tem tamanho 1

This is the shape before squeezing: torch.Size([2, 3, 1])
This is the shape after squeezing: torch.Size([2, 3])


In [18]:
a = torch.ones(2,3)
print(f"This is the shape before unsqueezing: {a.shape}")
squeezed = a.unsqueeze(2)
print(f"This is the shape after unsqueezing: {squeezed.shape}")  #adiciona uma dimensao de tamanho 1

This is the shape before unsqueezing: torch.Size([2, 3])
This is the shape after unsqueezing: torch.Size([2, 3, 1])


In [21]:
a = torch.ones(2,3) #matriz 2x3

In [22]:
a #print

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [20]:
print(a[None].shape) #cria uma diemnsao nova no indice 0
print(a[:,None].shape) #cria no indice 2
print(a[:,:,None].shape) #e no indice 3

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])
